name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: sshpass -p $RASPI_PASS ssh pi@$RASPI_IP ls
    env:
      RASPI_PASS: ${{secrets.RASPI_PASS}}
      RASPI_IP: ${{secrets.RASPI_IP}}
