name: test-on-pi
on: [push]
jobs:
  run-pi-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run pi tests
        run: mkdir -p ~/.ssh; ssh-keyscan -p "$TUNNEL_PORT" -H "$TUNNEL_ADDRESS" >> ~/.ssh/known_hosts; sshpass -p $TUNNEL_PASS ssh -o "StrictHostKeyChecking no" -p $TUNNEL_PORT $TUNNEL_USER@$TUNNEL_ADDRESS "./sshpass -p $RASPI_PASS ssh -p $RASPI_PORT pi@localhost \"set +o history; source .profile; ci_cmd \\\"$CI_CMD_ARG\\\" \\\"${GITHUB_REF#refs/heads/}\\\"\""
        env:
          TUNNEL_PASS: ${{secrets.TUNNEL_PASS}}
          TUNNEL_PORT: ${{secrets.TUNNEL_PORT}}
          TUNNEL_USER: ${{secrets.TUNNEL_USER}}
          TUNNEL_IP: ${{secrets.TUNNEL_IP}}
          TUNNEL_ADDRESS: ${{secrets.TUNNEL_ADDRESS}}
          RASPI_PASS: ${{secrets.RASPI_PASS}}
          RASPI_PORT: ${{secrets.RASPI_PORT}}
          CI_CMD_ARG: ${{secrets.CI_CMD_ARG}}
          TUNNEL_KNOWN_HOSTS: ${{secrets.TUNNEL_KNOWN_HOSTS}}
